### PR TITLE
Create backend_java challenge

### PR DESCRIPTION
**Pull request by MiguelCatalan**

### CODE REVIEW

**Comment by mayoral** [comment]
We have two options:

- We can rename the current `backend.md` to `backend_ruby.md`.
- We add the java specific requirements to `backend.md`: Something like 'The project must be done using either **Ruby**, **Elixir***, **Java** or **Kotlin**`, etc.

What do you prefer? :)

**Comment by MiguelCatalan** [comment]
@luisamor good catch I forgot to add the extension

**Comment by MiguelCatalan** [comment]
I would rather separate the code challenges in 2 files, just in case we want to focus on different stuff.

And also I would wait to rename the `backend.md` because there are some candidates doing the code challenge. And could be frustrating if the link to the challenge is broken.

What do you think?

**Comment by mayoral** [comment]
LGTM!

**Pull request merged**
